CPPFLAGS=-std=c++11 -O0

all: normal template constexpr mpl

normal: normal.cpp
	g++ $(CPPFLAGS) normal.cpp -o normal

template: template.cpp
	g++ $(CPPFLAGS) template.cpp -o template

constexpr: constexpr.cpp
	g++ $(CPPFLAGS) constexpr.cpp -o constexpr

mpl: mpl.cpp
	g++ $(CPPFLAGS) mpl.cpp -o mpl
