CPPFLAGS=-std=c++11 -O0

all: normal template constexpr

normal: normal.cpp
	g++ $(CPPFLAGS) normal.cpp -o normal

template: template.cpp
	g++ $(CPPFLAGS) template.cpp -o template

constexpr: constexpr.cpp
	g++ $(CPPFLAGS) constexpr.cpp -o constexpr
